name: responsiveweb
description: A new Flutter project.
publish_to: 'none' 
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  responsive_framework: ^0.1.5
  routemaster: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/videos/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/product_sans_regular.ttf
        - asset: assets/fonts/product_sans_bold.ttf
          weight: 700
        - asset: assets/fonts/product_sans_italic.ttf
          style: italic
    - family: Roboto
      fonts:
          - asset: assets/fonts/roboto_regular.ttf
          - asset: assets/fonts/roboto_bold.ttf
            weight: 700
          - asset: assets/fonts/roboto_italic.ttf
            style: italic